# Grafana admin password is 'admin'
grafana:
  adminPassword: "admin"
  datasources:
   datasources.yaml:
     apiVersion: 1
     datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.monitoring.svc.cluster.local
        jsonData:
          maxLines: 1000
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'demo' # Replace with your tenant ID string

prometheusOperator:
  admissionWebhooks:
    enabled: true
    certManager:
      enabled: true
