httpRoutes:  
  - name: kargo-api-http
    namespace: kargo
    parentRefs:
        - name: traefik-gateway # Gateway created by Traefik when the Gateway API provider is enabled
          sectionName: websecure
          namespace: traefik
    hostnames:
      - "kargo.localhost"
    rules:
      - backendRefs:
        - name: kargo-api
          port: 80