apiVersion: v1
kind: Secret
metadata:
  name: github-app
stringData:
  client_id: SXYyM2xpRlFNeFF5TTdISU1VTE8= # Set your ClientID here
  client_secret: NTg5Y2Q5ZGY4MGVlOGZhMDA4Yzg1NjdlNTFjN2NmMmQ4NmJhMWViMQ== # Set your client secret here