apiVersion: v1
kind: Secret
metadata:
  name: github-oidc-client
stringData:
  client_id: Ov23liyQBlAvjlKSApbo # Set your ClientID here
  client_secret: 7eabbba506321914e9ded5a51e706e61ec15245e # Set your client secret here