apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gowebservice
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chhayham/GoWebService
      path: helm-chart
      targetRevision: v1.0.7
      helm:
        releaseName: gowebservice
        valuesObject:
          service:
            port: 8080
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gowebservice
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: route-gowebservice
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chhayham/k3d-demo
      path: helm/httproute
      targetRevision: main
      helm:
        releaseName: route-gowebwervice
        valuesObject:
          httpRoutes:
            - name: gowebservice
              namespace: gowebservice
              parentRefs:
                - name: traefik-gateway
                  sectionName: websecure
                  namespace: traefik
              hostnames:
                - goweb.localhost
              rules:
                - backendRefs:
                    - name: gowebservice
                      port: 8080
              certResolver: le
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gowebservice
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true

