apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gowebservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chhayham/GoWebService'
    targetRevision: main          # Or a specific branch, commit hash, or tag
    path: helm-chart  # The folder path in Git where Chart.yam
    helm:
      releaseName: gowebservice
      valuesObject:
        service:
          type: NodePort
          port: 8080
          nodePort: 31202 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gowebservice
  syncPolicy:
    syncOptions:
    - CreateNamespace=true