apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp
      chart: headlamp
      targetRevision: 0.40.0
      helm:
        releaseName: headlamp
        valuesObject:
          service:
            port: 80
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: route-headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chhayham/k3d-demo
      path: helm/httproute
      targetRevision: main
      helm:
        releaseName: route-headlamp
        valuesObject:
          httpRoutes:
            - name: headlamp
              namespace: headlamp
              parentRefs:
                - name: traefik-gateway
                  sectionName: websecure
                  namespace: traefik
              hostnames:
                - k8s.localhost
              rules:
                - backendRefs:
                    - name: headlamp
                      port: 80
  destination:
    server: "https://kubernetes.default.svc"
    namespace: headlamp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true

