apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lemonade-server.fullname" . }}-pvc
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi # 200Gi is a safe bet for now, but can be adjusted based on the model size and usage.