configs:
  secret:
    argocdServerAdminPassword: $2a$10$5vm8wXaSdbuff0m9l21JdevzXBzJFPCi8sy6OOnpZMAG.fOXL7jvO

  params:
    server.insecure: true  # HTTPS backend

dex:
  enabled: false

notifications:
  enabled: false

global:
  domain: "argocd.localhost"

server:
  extensions:
    enabled: true
    extensionList:
      - name: argo-rollouts
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.7/extension.tar 

  httproute:
    enabled: true
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: websecure
    hostnames: 
      - argocd.localhost

  # backendTLSPolicy:
  #   enabled: true
  #   targetRefs:
  #     - group: ""
  #       kind: Service
  #       name: argocd-server
  #       sectionName: websecure
  #   validation:
  #     hostname: "argocd-server.argocd.svc.cluster.local"
  #     wellKnownCACertificates: System
